name: 'tests'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  run_wgo_tests:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Clone repo'
        uses: 'actions/checkout@v3'
      - name: 'Install go'
        uses: 'actions/setup-go@v4'
        with:
          go-version: '1.16.0'
      - run: 'go install github.com/mattn/goveralls@latest'
      - run: 'go test . -coverprofile=coverage -race'
      - run: 'goveralls -coverprofile=coverage -service=github'
        env:
          COVERALLS_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
